### PR TITLE
Fixed issues with TS definitions exporting

### PR DESCRIPTION
**Pull request by crutchcorn**
This fixes some of the issues brought up in #26

### CODE REVIEW

**Review by kyle-ssg — APPROVED** [review]
Ok, yep that looks good! I'll probably do a followup with your shared type suggestion, makes sense.

**Comment by kyle-ssg** [comment]
Version @0.2.4 released, thank you again!

**Comment by crutchcorn** [comment]
I've found some further issues with the TS typings that I didn't catch earlier. I have a PR incoming

**Comment by crutchcorn** [comment]
Those typing errors have been fixed in #32

**Pull request merged**
